/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   variables-preview-overlay.html
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/legacy/class.d.ts" />
/// <reference path="../polymer/types/lib/utils/render-status.d.ts" />
/// <reference path="../iron-overlay-behavior/iron-overlay-behavior.d.ts" />
/// <reference path="../paper-styles/shadow.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />
/// <reference path="../variables-consumer-mixin/variables-consumer-mixin.d.ts" />

declare namespace UiElements {

  /**
   * An element to display quick preview of variables values for current
   * environment.
   *
   * The element works with
   * [variables-manager](https://github.com/advanced-rest-client/variables-manager/)
   * that provides the events API to get information about environemnts and variables.
   * It also requires `advanced-rest-client/arc-models/variables-model` as an
   * access to the data store.
   *
   * The element renders an overlay controlled by `Polymer.IronOverlayBehavior`
   * with list of variables associated with current environment.
   *
   * It listens for `variables-list-changed` custom event dispatched by the
   * `variables-manager`.
   * If the event cannot be send by the application then set `variables` and
   * `environemnt` properties to the corresponding values.
   *
   * ### Example
   *
   * ```html
   * <variables-preview-overlay id="overlay"></variables-preview-overlay>
   * ```
   * ```javascript
   * document.getElementById('overlay').positionTarget = target; // HTML element
   * ```
   *
   * ### Styling
   *
   * `<variables-preview-overlay>` provides the following custom properties and
   * mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--variables-preview-overlay` | Mixin applied to the element | `{}`
   * `--variables-preview-overlay-background-color` | Background color of the oberlay | `inherit`
   * `--variables-preview-overlay-dialog-color` | Overlay foreground color | `--primary-text-color`
   * `--variables-preview-overlay-title` | Mixin applied to the title element | `{}`
   * `--variables-preview-overlay-var-name-color` | Color of a variable name label | `rgba(0, 0, 0, .54)`
   * `--variables-preview-overlay-var-value-color` | Color of a variable value label | `rgba(0, 0, 0, .87)`
   */
  class VariablesPreviewOverlay extends
    Polymer.IronOverlayBehavior(
    ArcComponents.VariablesConsumerMixin(
    Object)) {

    /**
     * List of application variables (stored in the data store + in memory)
     */
    appVariables: Array<object|null>|null;

    /**
     * List of system variables to display.
     */
    systemVariables: Array<object|null>|null;

    /**
     * Computed value, true if the element has application variables
     */
    readonly hasAppVariables: boolean|null|undefined;

    /**
     * Computed value, true if the element has system variables
     */
    readonly hasSysVariables: boolean|null|undefined;
    _computeVarsData(record: any): void;

    /**
     * Sort function for dom-repeat for vars
     */
    _varSort(a: object|null, b: object|null): Number|null;

    /**
     * Computes value for `has*Variables` properties.
     *
     * @param record Polymer's change record
     */
    _computeHasVars(record: object|null): Boolean|null;

    /**
     * Creates a list of application variables only (application + in mem vars)
     *
     * @param record Polymer's change record
     * @returns A list with filtered out system variables
     */
    _computeAppVars(record: object|null): Array<object|null>|null;

    /**
     * Creates a list of system variables.
     *
     * @param record Polymer's change record
     * @returns A list with system variables only.
     */
    _computeSysVars(record: object|null): Array<object|null>|null;
    _fireEdit(): void;
  }
}

interface HTMLElementTagNameMap {
  "variables-preview-overlay": UiElements.VariablesPreviewOverlay;
}
