/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/utils.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

export {varsSort};


/**
 * Sort function for dom-repeat for vars
 */
declare function varsSort(a: object|null, b: object|null): Number|null;

export {valueLabel};


/**
 * Computes value for a variable label depending on value of `maskedValues`.
 *
 * @returns When `maskedValues` is true then it returns series of `•`.
 * The input otherwise.
 */
declare function valueLabel(value: String|null, maskedValues: Boolean|null): String|null;
